[package]
name = "game_of_life"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
coil_engine = { path = "../coil_engine" }
crossterm = { workspace = true }
env_logger = "0.11.8"
log = "0.4.27"
rand = "0.9.1"
